<?php

/**
 * This is the model base class for the table "cms_rol".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsRol".
 *
 * Columns in table "cms_rol" available as properties of the model,
 * followed by relations of table "cms_rol" available as properties of the model.
 *
 * @property integer $idcmsrol
 * @property string $rol
 *
 * @property CmsPermissionRol[] $cmsPermissionRols
 * @property CmsUsuario[] $cmsUsuarios
 */
abstract class BaseCmsRol extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_rol';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Rol|Roles', $n);
	}

	public static function representingColumn() {
		return 'rol';
	}

	public function rules() {
		return array(
			array('rol', 'required'),
			array('rol', 'length', 'max'=>255),
			array('idcmsrol, rol', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cmsPermissionRols' => array(self::HAS_MANY, 'CmsPermissionRol', 'cms_rol_id'),
			'cmsUsuarios' => array(self::HAS_MANY, 'CmsUsuario', 'cms_rol_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcmsrol' => Yii::t('app', 'Idcmsrol'),
			'rol' => Yii::t('app', 'Rol'),
			'cmsPermissionRols' => null,
			'cmsUsuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcmsrol', $this->idcmsrol);
		$criteria->compare('rol', $this->rol, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}