<?php

/**
 * This is the model base class for the table "paymentypes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Paymentypes".
 *
 * Columns in table "paymentypes" available as properties of the model,
 * followed by relations of table "paymentypes" available as properties of the model.
 *
 * @property integer $idPaymentType
 * @property string $paymentTypeName
 *
 * @property Payments[] $payments
 */
abstract class BasePaymentypes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'paymentypes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Paymentypes|Paymentypes', $n);
	}

	public static function representingColumn() {
		return 'paymentTypeName';
	}

	public function rules() {
		return array(
			array('paymentTypeName', 'required'),
			array('paymentTypeName', 'length', 'max'=>45),
			array('idPaymentType, paymentTypeName', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'payments' => array(self::HAS_MANY, 'Payments', 'idPaymentType'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idPaymentType' => Yii::t('app', 'Id Payment Type'),
			'paymentTypeName' => Yii::t('app', 'Payment Type Name'),
			'payments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idPaymentType', $this->idPaymentType);
		$criteria->compare('paymentTypeName', $this->paymentTypeName, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}