<?php

/**
 * This is the model base class for the table "treedistricts".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Treedistricts".
 *
 * Columns in table "treedistricts" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idDistrict
 * @property string $fullDistrict
 *
 */
abstract class BaseTreedistricts extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'treedistricts';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Locación|Locación', $n);
	}

	public static function representingColumn() {
		return 'fullDistrict';
	}

	public function rules() {
		return array(
			array('idDistrict', 'length', 'max'=>20),
			array('fullDistrict', 'length', 'max'=>141),
			array('idDistrict, fullDistrict', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idDistrict, fullDistrict', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idDistrict' => Yii::t('app', 'Id District'),
			'fullDistrict' => Yii::t('app', 'Full District'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idDistrict', $this->idDistrict, true);
		$criteria->compare('fullDistrict', $this->fullDistrict, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}