<?php

/**
 * This is the model base class for the table "comments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comments".
 *
 * Columns in table "comments" available as properties of the model,
 * followed by relations of table "comments" available as properties of the model.
 *
 * @property string $idComment
 * @property string $comment
 * @property string $idWallet
 * @property string $idAdviser
 *
 * @property Advisers $idAdviser0
 * @property Wallets $idWallet0
 */
abstract class BaseComments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comments|Comments', $n);
	}

	public static function representingColumn() {
		return 'comment';
	}

	public function rules() {
		return array(
			array('comment, idWallet, idAdviser', 'required'),
			array('idWallet, idAdviser', 'length', 'max'=>20),
			array('idComment, comment, idWallet, idAdviser', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'advisers' => array(self::BELONGS_TO, 'Advisers', 'idAdviser'),
			'idWallet0' => array(self::BELONGS_TO, 'Wallets', 'idWallet'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idComment' => Yii::t('app', 'Id Comment'),
			'comment' => Yii::t('app', 'Comment'),
			'idWallet' => null,
			'idAdviser' => null,
			'idAdviser0' => null,
			'idWallet0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idComment', $this->idComment, true);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('idWallet', $this->idWallet);
		$criteria->compare('idAdviser', $this->idAdviser);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}