<?php

/**
 * This is the model base class for the table "coj_testimony".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CojTestimony".
 *
 * Columns in table "coj_testimony" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $img_es
 * @property string $img_en
 * @property string $testi_es
 * @property string $testi_en
 * @property string $name_company_es
 * @property string $name_company_en
 * @property string $name_person_es
 * @property string $name_person_en
 * @property string $charge_person_es
 * @property string $charge_person_en
 * @property string $dCreation
 * @property string $dUpdate
 *
 */
abstract class BaseCojTestimony extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'coj_testimony';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Testimonio|Testimonios', $n);
	}

	public static function representingColumn() {
		return 'img_es';
	}

	public function rules() {
		return array(
			array('img_es, img_en, testi_es, testi_en, name_company_es, name_company_en, name_person_es, name_person_en, charge_person_es, charge_person_en', 'required'),
			array('testi_es, testi_en', 'length', 'max'=>200),
			array('name_company_es, name_company_en, name_person_es, name_person_en', 'length', 'max'=>50),
			array('charge_person_es, charge_person_en', 'length', 'max'=>80),
			array('id, img_es, img_en, testi_es, testi_en, name_company_es, name_company_en, name_person_es, name_person_en, charge_person_es, charge_person_en, dCreation, dUpdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'img_es' => Yii::t('app', 'Imagen Español'),
			'img_en' => Yii::t('app', 'Imagen Ingles'),
			'testi_es' => Yii::t('app', 'Testimonio Español'),
			'testi_en' => Yii::t('app', 'Testimonio Ingles'),
			'name_company_es' => Yii::t('app', 'Nombre Compañia Español'),
			'name_company_en' => Yii::t('app', 'Nombre Compañia Ingles'),
			'name_person_es' => Yii::t('app', 'Nombre Persona Encargada Español'),
			'name_person_en' => Yii::t('app', 'Nombre Persona Encargada Ingles'),
			'charge_person_es' => Yii::t('app', 'Cargo Persona Encargada Español'),
			'charge_person_en' => Yii::t('app', 'Cargo Persona Encargada Ingles'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'dUpdate' => Yii::t('app', 'D Update'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('img_es', $this->img_es, true);
		$criteria->compare('img_en', $this->img_en, true);
		$criteria->compare('testi_es', $this->testi_es, true);
		$criteria->compare('testi_en', $this->testi_en, true);
		$criteria->compare('name_company_es', $this->name_company_es, true);
		$criteria->compare('name_company_en', $this->name_company_en, true);
		$criteria->compare('name_person_es', $this->name_person_es, true);
		$criteria->compare('name_person_en', $this->name_person_en, true);
		$criteria->compare('charge_person_es', $this->charge_person_es, true);
		$criteria->compare('charge_person_en', $this->charge_person_en, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('dUpdate', $this->dUpdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}