<?php

/**
 * This is the model base class for the table "coj_map".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CojMap".
 *
 * Columns in table "coj_map" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property double $latitude
 * @property double $lgn
 * @property string $title_en
 * @property string $title_es
 * @property string $dCreation
 * @property string $dUpdate
 *
 */
abstract class BaseCojMap extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'coj_map';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mapa|Mapas', $n);
	}

	public static function representingColumn() {
		return 'title_en';
	}

	public function rules() {
		return array(
			array('latitude, lgn, title_en, title_es', 'required'),
			array('latitude, lgn', 'numerical'),
			array('title_en, title_es', 'length', 'max'=>50),
			array('id, latitude, lgn, title_en, title_es, dCreation, dUpdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'latitude' => Yii::t('app', 'Latitude'),
			'lgn' => Yii::t('app', 'Longitud'),
			'title_en' => Yii::t('app', 'Título Ingles'),
			'title_es' => Yii::t('app', 'Título Español'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'dUpdate' => Yii::t('app', 'D Update'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('latitude', $this->latitude);
		$criteria->compare('lgn', $this->lgn);
		$criteria->compare('title_en', $this->title_en, true);
		$criteria->compare('title_es', $this->title_es, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('dUpdate', $this->dUpdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}