<?php

/**
 * This is the model base class for the table "token".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Token".
 *
 * Columns in table "token" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idToken
 * @property string $permision_key
 * @property string $date
 *
 */
abstract class BaseToken extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'token';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Token|Tokens', $n);
	}

	public static function representingColumn() {
		return 'permision_key';
	}

	public function rules() {
		return array(
			array('permision_key, date', 'required'),
			array('permision_key', 'length', 'max'=>32),
			array('idToken, permision_key, date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idToken' => Yii::t('app', 'Id Token'),
			'permision_key' => Yii::t('app', 'Permision Key'),
			'date' => Yii::t('app', 'Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idToken', $this->idToken, true);
		$criteria->compare('permision_key', $this->permision_key, true);
		$criteria->compare('date', $this->date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}