<?php

/**
 * This is the model base class for the table "agendas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Agenda".
 *
 * Columns in table "agendas" available as properties of the model,
 * followed by relations of table "agendas" available as properties of the model.
 *
 * @property string $idAgenda
 * @property string $action
 * @property string $dAction
 * @property string $dCreation
 * @property string $idWallet
 * @property string $idAdviser
 *
 * @property Advisers $idAdviser0
 * @property Wallets $idWallet0
 */
abstract class BaseAgenda extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'agendas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Agenda|Agendas', $n);
	}

	public static function representingColumn() {
		return 'action';
	}

	public function rules() {
		return array(
			array('action, dAction, dCreation, idWallet, idAdviser', 'required'),
			array('action', 'length', 'max'=>155),
			array('idWallet, idAdviser', 'length', 'max'=>20),
			array('idAgenda, action, dAction, dCreation, idWallet, idAdviser', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAdviser0' => array(self::BELONGS_TO, 'Advisers', 'idAdviser'),
			'idWallet0' => array(self::BELONGS_TO, 'Wallets', 'idWallet'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idAgenda' => Yii::t('app', 'Id Agenda'),
			'action' => Yii::t('app', 'Action'),
			'dAction' => Yii::t('app', 'D Action'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'idWallet' => null,
			'idAdviser' => null,
			'idAdviser0' => null,
			'idWallet0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idAgenda', $this->idAgenda, true);
		$criteria->compare('action', $this->action, true);
		$criteria->compare('dAction', $this->dAction, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('idWallet', $this->idWallet);
		$criteria->compare('idAdviser', $this->idAdviser);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}