<?php

/**
 * This is the model base class for the table "agendas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Agendas".
 *
 * Columns in table "agendas" available as properties of the model,
 * followed by relations of table "agendas" available as properties of the model.
 *
 * @property string $idAgenda
 * @property integer $idAction
 * @property string $dAction
 * @property string $dCreation
 * @property string $idWallet
 * @property string $idAdviser
 * @property integer $idEffect
 * @property string $comment
 *
 * @property Action $idAction0
 * @property Advisers $idAdviser0
 * @property Wallets $idWallet0
 * @property Effects $idEffect0
 */
abstract class BaseAgendas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'agendas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Agendas|Agendases', $n);
	}

	public static function representingColumn() {
		return 'dAction';
	}

	public function rules() {
		return array(
			array('idAction, dAction, idWallet, idAdviser, idEffect', 'required'),
			array('idAction, idEffect', 'numerical', 'integerOnly'=>true),
			array('idWallet, idAdviser', 'length', 'max'=>20),
			array('dCreation, comment', 'safe'),
			array('dCreation, comment', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idAgenda, idAction, dAction, dCreation, idWallet, idAdviser, idEffect, comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAction0' => array(self::BELONGS_TO, 'Action', 'idAction'),
			'idAdviser0' => array(self::BELONGS_TO, 'Advisers', 'idAdviser'),
			'idWallet0' => array(self::BELONGS_TO, 'Wallets', 'idWallet'),
			'idEffect0' => array(self::BELONGS_TO, 'Effects', 'idEffect'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idAgenda' => Yii::t('app', 'Id Agenda'),
			'idAction' => null,
			'dAction' => Yii::t('app', 'D Action'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'idWallet' => null,
			'idAdviser' => null,
			'idEffect' => null,
			'comment' => Yii::t('app', 'Comment'),
			'idAction0' => null,
			'idAdviser0' => null,
			'idWallet0' => null,
			'idEffect0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idAgenda', $this->idAgenda, true);
		$criteria->compare('idAction', $this->idAction);
		$criteria->compare('dAction', $this->dAction, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('idWallet', $this->idWallet);
		$criteria->compare('idAdviser', $this->idAdviser);
		$criteria->compare('idEffect', $this->idEffect);
		$criteria->compare('comment', $this->comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}