<?php

/**
 * This is the model base class for the table "cms_message_contact".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsMessageContact".
 *
 * Columns in table "cms_message_contact" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idMessageContact
 * @property string $name
 * @property string $email
 * @property string $subject
 * @property string $message
 *
 */
abstract class BaseCmsMessageContact extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_message_contact';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CmsMessageContact|CmsMessageContacts', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, email, subject, message', 'required'),
			array('name, subject', 'length', 'max'=>100),
			array('email', 'length', 'max'=>45),
			array('idMessageContact, name, email, subject, message', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idMessageContact' => Yii::t('app', 'Id Message Contact'),
			'name' => Yii::t('app', 'Name'),
			'email' => Yii::t('app', 'Email'),
			'subject' => Yii::t('app', 'Subject'),
			'message' => Yii::t('app', 'Message'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idMessageContact', $this->idMessageContact, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('subject', $this->subject, true);
		$criteria->compare('message', $this->message, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}