<?php

/**
 * This is the model base class for the table "viewadvisersstatus".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Viewadvisersstatus".
 *
 * Columns in table "viewadvisersstatus" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idAdviser
 * @property string $fullAdviser
 *
 */
abstract class BaseViewadvisersstatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'viewadvisersstatus';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Viewadvisersstatus|Viewadvisersstatuses', $n);
	}

	public static function representingColumn() {
		return 'fullAdviser';
	}

	public function rules() {
		return array(
			array('idAdviser', 'length', 'max'=>20),
			array('fullAdviser', 'length', 'max'=>261),
			array('idAdviser, fullAdviser', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idAdviser, fullAdviser', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idAdviser' => Yii::t('app', 'Id Adviser'),
			'fullAdviser' => Yii::t('app', 'Full Adviser'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idAdviser', $this->idAdviser, true);
		$criteria->compare('fullAdviser', $this->fullAdviser, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}