<?php

/**
 * This is the model base class for the table "payments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Payments".
 *
 * Columns in table "payments" available as properties of the model,
 * followed by relations of table "payments" available as properties of the model.
 *
 * @property string $idPayment
 * @property double $value
 * @property string $dPayment
 * @property string $dCreation
 * @property string $idWallet
 * @property string $idAdviser
 * @property integer $idPaymentType
 *
 * @property Advisers $idAdviser0
 * @property Wallets $idWallet0
 * @property Paymentypes $idPaymentType0
 */
abstract class BasePayments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'payments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Payments|Payments', $n);
	}

	public static function representingColumn() {
		return 'dPayment';
	}

	public function rules() {
		return array(
			array('value, dPayment, idWallet, idAdviser, idPaymentType', 'required'),
			array('idPaymentType', 'numerical', 'integerOnly'=>true),
			array('value', 'numerical'),
			array('idWallet, idAdviser', 'length', 'max'=>20),
			array('dCreation', 'safe'),
			array('dCreation', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idPayment, value, dPayment, dCreation, idWallet, idAdviser, idPaymentType', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAdviser0' => array(self::BELONGS_TO, 'Advisers', 'idAdviser'),
			'idWallet0' => array(self::BELONGS_TO, 'Wallets', 'idWallet'),
			'idPaymentType0' => array(self::BELONGS_TO, 'Paymentypes', 'idPaymentType'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idPayment' => Yii::t('app', 'Id Payment'),
			'value' => Yii::t('app', 'Value'),
			'dPayment' => Yii::t('app', 'D Payment'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'idWallet' => null,
			'idAdviser' => null,
			'idPaymentType' => null,
			'idAdviser0' => null,
			'idWallet0' => null,
			'idPaymentType0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idPayment', $this->idPayment, true);
		$criteria->compare('value', $this->value);
		$criteria->compare('dPayment', $this->dPayment, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('idWallet', $this->idWallet);
		$criteria->compare('idAdviser', $this->idAdviser);
		$criteria->compare('idPaymentType', $this->idPaymentType);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}