<?php

/**
 * This is the model base class for the table "cms_contact".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsContact".
 *
 * Columns in table "cms_contact" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idContact
 * @property string $address
 * @property string $nationalPhone
 * @property string $localPhone
 * @property string $email
 *
 */
abstract class BaseCmsContact extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_contact';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CmsContact|CmsContacts', $n);
	}

	public static function representingColumn() {
		return 'address';
	}

	public function rules() {
		return array(
			array('address, nationalPhone, localPhone, email', 'required'),
			array('address', 'length', 'max'=>255),
			array('nationalPhone', 'length', 'max'=>20),
			array('localPhone', 'length', 'max'=>10),
			array('email', 'length', 'max'=>45),
			array('idContact, address, nationalPhone, localPhone, email', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idContact' => Yii::t('app', 'Id Contact'),
			'address' => Yii::t('app', 'Address'),
			'nationalPhone' => Yii::t('app', 'National Phone'),
			'localPhone' => Yii::t('app', 'Local Phone'),
			'email' => Yii::t('app', 'Email'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idContact', $this->idContact, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('nationalPhone', $this->nationalPhone, true);
		$criteria->compare('localPhone', $this->localPhone, true);
		$criteria->compare('email', $this->email, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}