<?php

/**
 * This is the model base class for the table "cms_infomation".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsInfomation".
 *
 * Columns in table "cms_infomation" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idInformation
 * @property string $image
 * @property string $title
 * @property string $description
 *
 */
abstract class BaseCmsInfomation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_infomation';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CmsInfomation|CmsInfomations', $n);
	}

	public static function representingColumn() {
		return 'image';
	}

	public function rules() {
		return array(
			array('image, title, description', 'required'),
			array('image, description', 'length', 'max'=>255),
			array('title', 'length', 'max'=>100),
			array('idInformation, image, title, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idInformation' => Yii::t('app', 'Id Information'),
			'image' => Yii::t('app', 'Image'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idInformation', $this->idInformation, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}