<?php

/**
 * This is the model base class for the table "cms_permission_rol".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsPermissionRol".
 *
 * Columns in table "cms_permission_rol" available as properties of the model,
 * followed by relations of table "cms_permission_rol" available as properties of the model.
 *
 * @property integer $idcmspermissionrol
 * @property integer $cms_rol_id
 * @property string $controller
 * @property string $action
 *
 * @property CmsRol $cmsRol
 */
abstract class BaseCmsPermissionRol extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_permission_rol';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Permiso para Rol|Permisos para Roles', $n);
	}

	public static function representingColumn() {
		return 'controller';
	}

	public function rules() {
		return array(
			array('cms_rol_id, controller, action', 'required'),
			array('cms_rol_id', 'numerical', 'integerOnly'=>true),
			array('controller, action', 'length', 'max'=>255),
			array('idcmspermissionrol, cms_rol_id, controller, action', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cmsRol' => array(self::BELONGS_TO, 'CmsRol', 'cms_rol_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcmspermissionrol' => Yii::t('app', 'Idcmspermissionrol'),
			'cms_rol_id' => null,
			'controller' => Yii::t('app', 'Controlador'),
			'action' => Yii::t('app', 'Accción'),
			'cmsRol' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcmspermissionrol', $this->idcmspermissionrol);
		$criteria->compare('cms_rol_id', $this->cms_rol_id);
		$criteria->compare('controller', $this->controller, true);
		$criteria->compare('action', $this->action, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}