<?php

/**
 * This is the model base class for the table "coj_services".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CojServices".
 *
 * Columns in table "coj_services" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $img_es
 * @property string $img_en
 * @property string $title_es
 * @property string $title_en
 * @property string $dCreation
 * @property string $dUpdate
 *
 */
abstract class BaseCojServices extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'coj_services';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Servicio|Servicios', $n);
	}

	public static function representingColumn() {
		return 'img_es';
	}

	public function rules() {
		return array(
			array('img_es, img_en, title_es, title_en, subtitle_es, subtitle_en, des_es, des_en', 'required'),
			array('title_es, title_en', 'length', 'max'=>50),
			array('subtitle_es, subtitle_en', 'length', 'max'=>50),
			array('des_es, des_en', 'length', 'max'=>700),
			//array('title_es, title_en', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, img_es, img_en, title_es, title_en, subtitle_es, subtitle_en, des_es, des_en, dCreation, dUpdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'img_es' => Yii::t('app', 'Imagen Español'),
			'img_en' => Yii::t('app', 'Imagen Ingles'),
			'title_es' => Yii::t('app', 'Título Español'),
			'title_en' => Yii::t('app', 'Título Ingles'),
			'subtitle_es' => Yii::t('app', 'Subtitulo Español'),
			'subtitle_en' => Yii::t('app', 'Subtitulo Ingles'),
			'des_es' => Yii::t('app', 'Descripcion Español'),
			'des_en' => Yii::t('app', 'Descripcion Ingles'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'dUpdate' => Yii::t('app', 'D Update'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('img_es', $this->img_es, true);
		$criteria->compare('img_en', $this->img_en, true);
		$criteria->compare('title_es', $this->title_es, true);
		$criteria->compare('title_en', $this->title_en, true);
		$criteria->compare('subtitle_es', $this->subtitle_es, true);
		$criteria->compare('subtitle_en', $this->subtitle_en, true);
		$criteria->compare('des_es', $this->des_es, true);
		$criteria->compare('des_en', $this->des_en, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('dUpdate', $this->dUpdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}