<?php

/**
 * This is the model base class for the table "assettypes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Assettypes".
 *
 * Columns in table "assettypes" available as properties of the model,
 * followed by relations of table "assettypes" available as properties of the model.
 *
 * @property integer $idAssetType
 * @property string $assetTypeName
 *
 * @property Assets[] $assets
 */
abstract class BaseAssettypes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'assettypes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Assettypes|Assettypes', $n);
	}

	public static function representingColumn() {
		return 'assetTypeName';
	}

	public function rules() {
		return array(
			array('assetTypeName', 'required'),
			array('assetTypeName', 'length', 'max'=>155),
			array('idAssetType, assetTypeName', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'assets' => array(self::HAS_MANY, 'Assets', 'idType'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idAssetType' => Yii::t('app', 'Id Asset Type'),
			'assetTypeName' => Yii::t('app', 'Asset Type Name'),
			'assets' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idAssetType', $this->idAssetType);
		$criteria->compare('assetTypeName', $this->assetTypeName, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}