<?php

/**
 * This is the model base class for the table "cms_configuracion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsConfiguracion".
 *
 * Columns in table "cms_configuracion" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idcmsconfiguracion
 * @property string $empresa
 * @property string $host
 * @property string $encryption
 * @property string $nombre_correo
 * @property string $username
 * @property string $password
 * @property string $apiKey
 * @property string $port
 * @property string $plantilla
 * @property string $fecha_actualizacion
 * @property integer $usuario_actualiza
 * @property string $user_restful
 * @property string $password_restful
 *
 */
abstract class BaseCmsConfiguracion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_configuracion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Configuración|Configuración', $n);
	}

	public static function representingColumn() {
		return 'empresa';
	}
        
        public function beforeSave() {
            $this->fecha_actualizacion = new CDbExpression('NOW()');
            $this->usuario_actualiza = Yii::app()->user->getId();
            return parent::beforeSave();
        }

	public function rules() {
		return array(
			array('host, nombre_correo, username, password, apiKey, port, plantilla', 'required'),
			array('usuario_actualiza', 'numerical', 'integerOnly'=>true),
			array('empresa, nombre_correo, user_restful, password_restful', 'length', 'max'=>255),
                        array('username', 'unique'),
                        array('username', 'email'),
			array('host', 'length', 'max'=>60),
			array('encryption', 'length', 'max'=>20),
			array('username', 'length', 'max'=>70),
			array('password', 'length', 'max'=>100),
			array('port', 'length', 'max'=>10),
			array('empresa, encryption, usuario_actualiza, user_restful, password_restful', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcmsconfiguracion, empresa, host, encryption, nombre_correo, username, password, apiKey, port, plantilla, fecha_actualizacion, usuario_actualiza, user_restful, password_restful', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcmsconfiguracion' => Yii::t('app', 'Idcmsconfiguracion'),
			'empresa' => Yii::t('app', 'Empresa'),
			'host' => Yii::t('app', 'Host'),
			'encryption' => Yii::t('app', 'Encryption'),
			'nombre_correo' => Yii::t('app', 'Nombre Correo'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'apiKey' => Yii::t('app', 'Api Key'),
			'port' => Yii::t('app', 'Port'),
			'plantilla' => Yii::t('app', 'Plantilla'),
			'fecha_actualizacion' => Yii::t('app', 'Fecha Actualización'),
			'usuario_actualiza' => Yii::t('app', 'Usuario Actualiza'),
                        'user_restful' => Yii::t('app', 'User Restful'),
			'password_restful' => Yii::t('app', 'Password Restful'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcmsconfiguracion', $this->idcmsconfiguracion);
		$criteria->compare('empresa', $this->empresa, true);
		$criteria->compare('host', $this->host, true);
		$criteria->compare('encryption', $this->encryption, true);
		$criteria->compare('nombre_correo', $this->nombre_correo, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('apiKey', $this->apiKey, true);
		$criteria->compare('port', $this->port, true);
		$criteria->compare('plantilla', $this->plantilla, true);
		$criteria->compare('fecha_actualizacion', $this->fecha_actualizacion, true);
		$criteria->compare('usuario_actualiza', $this->usuario_actualiza);
                $criteria->compare('user_restful', $this->user_restful, true);
		$criteria->compare('password_restful', $this->password_restful, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}