<?php

/**
 * This is the model base class for the table "coj_footer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CojFooter".
 *
 * Columns in table "coj_footer" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $title_en
 * @property string $title_es
 * @property string $dCreation
 * @property string $dUpdate
 *
 */
abstract class BaseCojFooter extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'coj_footer';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Pie de Página|Pie de Paginas', $n);
	}

	public static function representingColumn() {
		return 'title_en';
	}

	public function rules() {
		return array(
			array('title_en, title_es', 'required'),
			array('title_en, title_es', 'length', 'max'=>30),
			array('id, title_en, title_es, dCreation, dUpdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title_en' => Yii::t('app', 'Título Ingles'),
			'title_es' => Yii::t('app', 'Título Español'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'dUpdate' => Yii::t('app', 'D Update'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('title_en', $this->title_en, true);
		$criteria->compare('title_es', $this->title_es, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('dUpdate', $this->dUpdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}