<?php

/**
 * This is the model base class for the table "coj_company".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CojCompany".
 *
 * Columns in table "coj_company" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $title_es
 * @property string $title_en
 * @property string $img_es
 * @property string $img_en
 * @property string $dCreation
 * @property string $dUpdate
 *
 */
abstract class BaseCojCompany extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'coj_company';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Empresa|Empresas', $n);
	}

	public static function representingColumn() {
		return 'img_es';
	}

	public function rules() {
		return array(
			array('img_es, img_en,', 'required'),
			array('title_es, title_en', 'length', 'max'=>50),
			array('title_es, title_en', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title_es, title_en, img_es, img_en, dCreation, dUpdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title_es' => Yii::t('app', 'Título Español'),
			'title_en' => Yii::t('app', 'Título Ingles'),
			'img_es' => Yii::t('app', 'Imagen Español'),
			'img_en' => Yii::t('app', 'Imagen Ingles'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'dUpdate' => Yii::t('app', 'D Update'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('title_es', $this->title_es, true);
		$criteria->compare('title_en', $this->title_en, true);
		$criteria->compare('img_es', $this->img_es, true);
		$criteria->compare('img_en', $this->img_en, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('dUpdate', $this->dUpdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}