<?php

/**
 * This is the model base class for the table "wallets_has_campaigns".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WalletsHasCampaigns".
 *
 * Columns in table "wallets_has_campaigns" available as properties of the model,
 * followed by relations of table "wallets_has_campaigns" available as properties of the model.
 *
 * @property string $idWallet
 * @property string $idCampaign
 * @property string $idWalletsHasCampaigns
 *
 * @property Campaigns $idCampaign0
 * @property Wallets $idWallet0
 */
abstract class BaseWalletsHasCampaigns extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'wallets_has_campaigns';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Deudores a Campañas|Deudores a Campañas', $n);
	}

	public static function representingColumn() {
		return 'idWalletsHasCampaigns';
	}

	public function rules() {
		return array(
			array('idWallet, idCampaign', 'required'),
			array('idWallet, idCampaign', 'length', 'max'=>20),
			array('idWallet, idCampaign, idWalletsHasCampaigns', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCampaign0' => array(self::BELONGS_TO, 'Campaigns', 'idCampaign'),
			'idWallet0' => array(self::BELONGS_TO, 'Wallets', 'idWallet'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idWallet' => 'Deudores',
			'idCampaign' => 'Nombre Campaña',
			'idWalletsHasCampaigns' => Yii::t('app', 'Id Wallets Has Campaigns'),
			'idCampaign0' => null,
			'idWallet0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idWallet', $this->idWallet);
		$criteria->compare('idCampaign', $this->idCampaign);
		$criteria->compare('idWalletsHasCampaigns', $this->idWalletsHasCampaigns, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}