<?php

/**
 * This is the model base class for the table "actions_has_effects".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ActionsHasEffects".
 *
 * Columns in table "actions_has_effects" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idActionsHasEffects
 * @property integer $idAction
 * @property integer $idEffect
 *
 */
abstract class BaseActionsHasEffects extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'actions_has_effects';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Acciones a Efectos|Acciones a Efectos', $n);
	}

	public static function representingColumn() {
		return 'idActionsHasEffects';
	}

	public function rules() {
		return array(
			array('idAction, idEffect', 'required'),
			array('idAction, idEffect', 'numerical', 'integerOnly'=>true),
			array('idActionsHasEffects, idAction, idEffect', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAction' => array(self::BELONGS_TO, 'Action', 'idAction'),
			'idEffect' => array(self::BELONGS_TO, 'Effect', 'idEffect'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idActionsHasEffects' => Yii::t('app', 'Id Actions Has Effects'),
			'idAction' => Yii::t('app', 'Acción'),
			'idEffect' => Yii::t('app', 'Efecto'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idActionsHasEffects', $this->idActionsHasEffects, true);
		$criteria->compare('idAction', $this->idAction);
		$criteria->compare('idEffect', $this->idEffect);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}