<?php

/**
 * This is the model base class for the table "cms_generic_text".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsGenericText".
 *
 * Columns in table "cms_generic_text" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idGenericText
 * @property string $text
 * @property string $image
 * @property string $subtitle
 *
 */
abstract class BaseCmsGenericText extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_generic_text';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CmsGenericText|CmsGenericTexts', $n);
	}

	public static function representingColumn() {
		return 'text';
	}

	public function rules() {
		return array(
			array('text', 'required'),
			array('text, image, subtitle', 'length', 'max'=>255),
			array('image, subtitle', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idGenericText, text, image, subtitle', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idGenericText' => Yii::t('app', 'Id Generic Text'),
			'text' => Yii::t('app', 'Text'),
			'image' => Yii::t('app', 'Image'),
			'subtitle' => Yii::t('app', 'Subtitle'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idGenericText', $this->idGenericText, true);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('subtitle', $this->subtitle, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}