<?php

/**
 * This is the model base class for the table "AuthItemChild".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AuthItemChild".
 *
 * Columns in table "AuthItemChild" available as properties of the model,
 * followed by relations of table "AuthItemChild" available as properties of the model.
 *
 * @property string $parent
 * @property string $child
 * @property string $idAuthItemChild
 *
 * @property AuthItem $parent0
 * @property AuthItem $child0
 */
abstract class BaseAuthItemChild extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'authitemchild';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AuthItemChild|AuthItemChildren', $n);
	}

	public static function representingColumn() {
		return 'parent';
	}

	public function rules() {
		return array(
			array('parent, child', 'required'),
			array('parent, child', 'length', 'max'=>64),
			array('parent, child, idAuthItemChild', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'parent0' => array(self::BELONGS_TO, 'AuthItem', 'parent'),
			'child0' => array(self::BELONGS_TO, 'AuthItem', 'child'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'parent' => null,
			'child' => null,
			'idAuthItemChild' => Yii::t('app', 'Id Auth Item Child'),
			'parent0' => null,
			'child0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('parent', $this->parent);
		$criteria->compare('child', $this->child);
		$criteria->compare('idAuthItemChild', $this->idAuthItemChild, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}