<?php

/**
 * This is the model base class for the table "coj_generictext".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CojGenerictext".
 *
 * Columns in table "coj_generictext" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $text_es
 * @property string $text_en
 * @property string $dCreate
 * @property string $dUpdate
 *
 */
abstract class BaseCojGenerictext extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'coj_generictext';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CojGenerictext|CojGenerictexts', $n);
	}

	public static function representingColumn() {
		return 'text_es';
	}

	public function rules() {
		return array(
			array('text_es, text_en, dCreate, dUpdate', 'required'),
			array('id, text_es, text_en, dCreate, dUpdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'text_es' => Yii::t('app', 'Text Es'),
			'text_en' => Yii::t('app', 'Text En'),
			'dCreate' => Yii::t('app', 'D Create'),
			'dUpdate' => Yii::t('app', 'D Update'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('text_es', $this->text_es, true);
		$criteria->compare('text_en', $this->text_en, true);
		$criteria->compare('dCreate', $this->dCreate, true);
		$criteria->compare('dUpdate', $this->dUpdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}