<?php

/**
 * This is the model base class for the table "departaments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Departaments".
 *
 * Columns in table "departaments" available as properties of the model,
 * followed by relations of table "departaments" available as properties of the model.
 *
 * @property string $idDepartament
 * @property string $name
 *
 * @property Cities[] $cities
 */
abstract class BaseDepartaments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'departaments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Departaments|Departaments', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>45),
			array('idDepartament, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cities' => array(self::HAS_MANY, 'Cities', 'idDepartament'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idDepartament' => Yii::t('app', 'Id Departament'),
			'name' => Yii::t('app', 'Name'),
			'cities' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idDepartament', $this->idDepartament, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}