<?php

/**
 * This is the model base class for the table "assets".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Assets".
 *
 * Columns in table "assets" available as properties of the model,
 * followed by relations of table "assets" available as properties of the model.
 *
 * @property integer $idAsset
 * @property string $description
 * @property string $dCreation
 * @property string $idWallet
 * @property string $idAdviser
 * @property integer $idType
 * @property string $assetName
 *
 * @property Assettypes $idType0
 * @property Advisers $idAdviser0
 * @property Wallets $idWallet0
 */
abstract class BaseAssets extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'assets';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Assets|Assets', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description, dCreation, idWallet, idAdviser, idType, assetName', 'required'),
			array('idType', 'numerical', 'integerOnly'=>true),
			array('idWallet, idAdviser', 'length', 'max'=>20),
			array('assetName', 'length', 'max'=>155),
			array('idAsset, description, dCreation, idWallet, idAdviser, idType, assetName', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idType0' => array(self::BELONGS_TO, 'Assettypes', 'idType'),
			'idAdviser0' => array(self::BELONGS_TO, 'Advisers', 'idAdviser'),
			'idWallet0' => array(self::BELONGS_TO, 'Wallets', 'idWallet'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idAsset' => Yii::t('app', 'Id Asset'),
			'description' => Yii::t('app', 'Description'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'idWallet' => null,
			'idAdviser' => null,
			'idType' => null,
			'assetName' => Yii::t('app', 'Asset Name'),
			'idType0' => null,
			'idAdviser0' => null,
			'idWallet0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idAsset', $this->idAsset);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('idWallet', $this->idWallet);
		$criteria->compare('idAdviser', $this->idAdviser);
		$criteria->compare('idType', $this->idType);
		$criteria->compare('assetName', $this->assetName, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}