<?php

/**
 * This is the model base class for the table "cms_icono".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsIcono".
 *
 * Columns in table "cms_icono" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idcmsicono
 * @property string $icono_class
 *
 */
abstract class BaseCmsIcono extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_icono';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Icono|Iconos', $n);
	}

	public static function representingColumn() {
		return 'icono_class';
	}

	public function rules() {
		return array(
			array('icono_class', 'required'),
			array('icono_class', 'length', 'max'=>40),
			array('idcmsicono, icono_class', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcmsicono' => Yii::t('app', 'Idcmsicono'),
			'icono_class' => Yii::t('app', 'Icono Class'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcmsicono', $this->idcmsicono);
		$criteria->compare('icono_class', $this->icono_class, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}