<?php

/**
 * This is the model base class for the table "cms_help".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsHelp".
 *
 * Columns in table "cms_help" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idcmshelp
 * @property string $titulo
 * @property string $contenido
 * @property string $link
 * @property string $fecha_creacion
 *
 */
abstract class BaseCmsHelp extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_help';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ayuda|Ayudas', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('titulo', 'required'),
			array('titulo', 'length', 'max'=>255),
			array('contenido, link', 'safe'),
                        array('link', 'url'),
			array('contenido, link', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcmshelp, titulo, contenido, link, fecha_creacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcmshelp' => Yii::t('app', 'Idcmshelp'),
			'titulo' => Yii::t('app', 'Título'),
			'contenido' => Yii::t('app', 'Contenido'),
			'link' => Yii::t('app', 'Link'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creación'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcmshelp', $this->idcmshelp);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('contenido', $this->contenido, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}