<?php

/**
 * This is the model base class for the table "coj_message".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CojMessage".
 *
 * Columns in table "coj_message" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property string $email
 * @property string $affair
 * @property string $mess
 * @property string $dCreation
 * @property string $dUpdate
 *
 */
abstract class BaseCojMessage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'coj_message';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mensaje|Mensajes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, email, affair, mess', 'required'),
			array('name', 'length', 'max'=>100),
			array('email', 'length', 'max'=>50),
			array('affair', 'length', 'max'=>60),
			array('mess', 'length', 'max'=>300),
			array('id, name, email, affair, mess, dCreation, dUpdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'email' => Yii::t('app', 'Email'),
			'affair' => Yii::t('app', 'Affair'),
			'mess' => Yii::t('app', 'Mess'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'dUpdate' => Yii::t('app', 'D Update'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('affair', $this->affair, true);
		$criteria->compare('mess', $this->mess, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('dUpdate', $this->dUpdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}