<?php

/**
 * This is the model base class for the table "effects".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Effects".
 *
 * Columns in table "effects" available as properties of the model,
 * followed by relations of table "effects" available as properties of the model.
 *
 * @property integer $idEffect
 * @property string $effectName
 *
 * @property Action[] $actions
 */
abstract class BaseEffects extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'effects';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Effects|Effects', $n);
	}

	public static function representingColumn() {
		return 'effectName';
	}

	public function rules() {
		return array(
			array('effectName', 'required'),
			array('effectName', 'length', 'max'=>155),
			array('idEffect, effectName', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'actions' => array(self::MANY_MANY, 'Action', 'actions_has_effects(idEffect, idAction)'),
		);
	}

	public function pivotModels() {
		return array(
			'actions' => 'ActionsHasEffects',
		);
	}

	public function attributeLabels() {
		return array(
			'idEffect' => Yii::t('app', 'Id Effect'),
			'effectName' => Yii::t('app', 'Effect Name'),
			'actions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idEffect', $this->idEffect);
		$criteria->compare('effectName', $this->effectName, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}