<?php

/**
 * This is the model base class for the table "coj_contact".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CojContact".
 *
 * Columns in table "coj_contact" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $hotlines_es
 * @property string $hotlines_en
 * @property string $addres_es
 * @property string $addres_en
 * @property string $email_es
 * @property string $email_en
 * @property string $contact_email
 * @property string $dCreation
 * @property string $dUpdate
 *
 */
abstract class BaseCojContact extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'coj_contact';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Contacto|Contactos', $n);
	}

	public static function representingColumn() {
		return 'hotlines_es';
	}

	public function rules() {
		return array(
			array('hotlines_es, hotlines_en, email_es, email_en, addres_es, addres_en, contact_email', 'required'),
			array('hotlines_es, hotlines_en, email_es, email_en', 'length', 'max'=>45),
			array('addres_es, addres_en', 'length', 'max'=>150),
			array('contact_email', 'length', 'max'=>50),
			array('dCreation, dUpdate', 'safe'),
			array('hotlines_es, hotlines_en, addres_es, addres_en, email_es, email_en, contact_email, dCreation, dUpdate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, hotlines_es, hotlines_en, addres_es, addres_en, email_es, email_en, contact_email, dCreation, dUpdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'hotlines_es' => Yii::t('app', 'Lineas de Contacto Español'),
			'hotlines_en' => Yii::t('app', 'Lineas de Contacto Ingles'),
			'addres_es' => Yii::t('app', 'Dirección Español'),
			'addres_en' => Yii::t('app', 'Dirección Ingles'),
			'email_es' => Yii::t('app', 'Correo Electronico Español'),
			'email_en' => Yii::t('app', 'Correo Electronico Ingles'),
			'contact_email' => Yii::t('app', 'Correo Electronico de Contacto'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'dUpdate' => Yii::t('app', 'D Update'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('hotlines_es', $this->hotlines_es, true);
		$criteria->compare('hotlines_en', $this->hotlines_en, true);
		$criteria->compare('addres_es', $this->addres_es, true);
		$criteria->compare('addres_en', $this->addres_en, true);
		$criteria->compare('email_es', $this->email_es, true);
		$criteria->compare('email_en', $this->email_en, true);
		$criteria->compare('contact_email', $this->contact_email, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('dUpdate', $this->dUpdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}