<?php

/**
 * This is the model base class for the table "cms_testimonial".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsTestimonial".
 *
 * Columns in table "cms_testimonial" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idTestimonial
 * @property string $position
 * @property string $description
 * @property string $name
 * @property string $image
 *
 */
abstract class BaseCmsTestimonial extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_testimonial';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CmsTestimonial|CmsTestimonials', $n);
	}

	public static function representingColumn() {
		return 'position';
	}

	public function rules() {
		return array(
			array('position, description, name, image', 'required'),
			array('position', 'length', 'max'=>50),
			array('description', 'length', 'max'=>500),
			array('name', 'length', 'max'=>100),
			array('image', 'length', 'max'=>255),
			array('idTestimonial, position, description, name, image', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idTestimonial' => Yii::t('app', 'Id Testimonial'),
			'position' => Yii::t('app', 'Position'),
			'description' => Yii::t('app', 'Description'),
			'name' => Yii::t('app', 'Name'),
			'image' => Yii::t('app', 'Image'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idTestimonial', $this->idTestimonial, true);
		$criteria->compare('position', $this->position, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('image', $this->image, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}