<?php

/**
 * This is the model base class for the table "tasks".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tasks".
 *
 * Columns in table "tasks" available as properties of the model,
 * followed by relations of table "tasks" available as properties of the model.
 *
 * @property integer $idTasks
 * @property string $idWallet
 * @property integer $idAction
 * @property string $dTask
 * @property string $dCreation
 * @property string $idAdviser
 *
 * @property Action $idAction0
 * @property Advisers $idAdviser0
 * @property Wallets $idWallet0
 */
abstract class BaseTasks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tasks';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tasks|Tasks', $n);
	}

	public static function representingColumn() {
		return 'dTask';
	}

	public function rules() {
		return array(
			array('idWallet, idAction, dTask, dCreation, idAdviser', 'required'),
			array('idAction', 'numerical', 'integerOnly'=>true),
			array('idWallet, idAdviser', 'length', 'max'=>20),
			array('idTasks, idWallet, idAction, dTask, dCreation, idAdviser', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAction0' => array(self::BELONGS_TO, 'Action', 'idAction'),
			'idAdviser0' => array(self::BELONGS_TO, 'Advisers', 'idAdviser'),
			'idWallet0' => array(self::BELONGS_TO, 'Wallets', 'idWallet'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idTasks' => Yii::t('app', 'Id Tasks'),
			'idWallet' => null,
			'idAction' => null,
			'dTask' => Yii::t('app', 'D Task'),
			'dCreation' => Yii::t('app', 'D Creation'),
			'idAdviser' => null,
			'idAction0' => null,
			'idAdviser0' => null,
			'idWallet0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idTasks', $this->idTasks);
		$criteria->compare('idWallet', $this->idWallet);
		$criteria->compare('idAction', $this->idAction);
		$criteria->compare('dTask', $this->dTask, true);
		$criteria->compare('dCreation', $this->dCreation, true);
		$criteria->compare('idAdviser', $this->idAdviser);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}