<?php

/**
 * This is the model base class for the table "lastpayments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Lastpayments".
 *
 * Columns in table "lastpayments" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idWallet
 * @property string $dPayment
 *
 */
abstract class BaseLastpayments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lastpayments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Lastpayments|Lastpayments', $n);
	}

	public static function representingColumn() {
		return 'dPayment';
	}

	public function rules() {
		return array(
			array('idWallet', 'required'),
			array('idWallet', 'length', 'max'=>20),
			array('dPayment', 'safe'),
			array('dPayment', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idWallet, dPayment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idWallet' => Yii::t('app', 'Id Wallet'),
			'dPayment' => Yii::t('app', 'D Payment'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idWallet', $this->idWallet, true);
		$criteria->compare('dPayment', $this->dPayment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}