<?php

/**
 * This is the model base class for the table "cms_coverage".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsCoverage".
 *
 * Columns in table "cms_coverage" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idCoverage
 * @property string $googleDirection
 *
 */
abstract class BaseCmsCoverage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_coverage';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CmsCoverage|CmsCoverages', $n);
	}

	public static function representingColumn() {
		return 'googleDirection';
	}

	public function rules() {
		return array(
			array('googleDirection', 'required'),
			array('googleDirection', 'length', 'max'=>45),
			array('idCoverage, googleDirection', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idCoverage' => Yii::t('app', 'Id Coverage'),
			'googleDirection' => Yii::t('app', 'Google Direction'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idCoverage', $this->idCoverage, true);
		$criteria->compare('googleDirection', $this->googleDirection, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}