<?php

/**
 * This is the model base class for the table "tempo_campaigns".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TempoCampaigns".
 *
 * Columns in table "tempo_campaigns" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $isTempo
 * @property string $name
 * @property string $companyName
 * @property string $idNumber
 * @property string $address
 * @property string $contactName
 * @property string $contactEmail
 * @property string $passwd
 * @property integer $active
 * @property string $phone
 * @property string $lote
 *
 */
abstract class BaseTempoCampaigns extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tempo_campaigns';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Prospectos|Prospectos', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, companyName, idNumber, address, contactName, contactEmail, lote', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('name, idNumber, contactName, passwd', 'length', 'max'=>45),
			array('companyName', 'length', 'max'=>55),
			array('address, lote', 'length', 'max'=>255),
			array('contactEmail', 'length', 'max'=>155),
			array('phone', 'length', 'max'=>12),
			array('active, phone', 'default', 'setOnEmpty' => true, 'value' => null),
			array('isTempo, name, companyName, idNumber, address, contactName, contactEmail, passwd, active, phone, lote', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'isTempo' => Yii::t('app', 'Is Tempo'),
			'name' => Yii::t('app', 'Nombre Campaña'),
			'companyName' => Yii::t('app', 'Nombre empresa'),
			'idNumber' => Yii::t('app', 'CC-NIT'),
			'address' => Yii::t('app', 'Dirección'),
			'contactName' => Yii::t('app', 'Nombre Contacto'),
			'contactEmail' => Yii::t('app', 'Correo Contacto'),
			'active' => Yii::t('app', 'Activo'),
			'phone' => Yii::t('app', 'Teléfono'),
			'lote' => Yii::t('app', 'Lote'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('isTempo', $this->isTempo, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('companyName', $this->companyName, true);
		$criteria->compare('idNumber', $this->idNumber, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('contactName', $this->contactName, true);
		$criteria->compare('contactEmail', $this->contactEmail, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('lote', $this->lote, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}