<?php

/**
 * This is the model base class for the table "viewwaletsidentification".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Viewwaletsidentification".
 *
 * Columns in table "viewwaletsidentification" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idWallet
 * @property string $identificationsWallet
 *
 */
abstract class BaseViewwaletsidentification extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'viewwaletsidentification';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Viewwaletsidentification|Viewwaletsidentifications', $n);
	}

	public static function representingColumn() {
		return 'identificationsWallet';
	}

	public function rules() {
		return array(
			array('idWallet', 'length', 'max'=>20),
			array('identificationsWallet', 'length', 'max'=>303),
			array('idWallet, identificationsWallet', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idWallet, identificationsWallet', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idWallet' => Yii::t('app', 'Id Wallet'),
			'identificationsWallet' => Yii::t('app', 'Identifications Wallet'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idWallet', $this->idWallet, true);
		$criteria->compare('identificationsWallet', $this->identificationsWallet, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}